Added Traditional Chinese (zh_tw.json)
DeeChael/Concentration pull request #16
Opened 2024-07-03 14:52 UTC by yichifauzi

Add Traditional Chinese translations

2024-07-05 12:19 UTC, notlin4 requested changes

2024-07-05 12:19 UTC, notlin4 commented on common/src/main/resources/assets/concentration/lang/zh_tw.json
> +  "concentration.config.customization.enabled": "啟用自訂",
```suggestion
  "concentration.config.customization.enabled": "啟用客製化",
```

2024-07-05 12:19 UTC, notlin4 commented on common/src/main/resources/assets/concentration/lang/zh_tw.json
> +  "concentration.option.fullscreen_mode.tooltip": "全螢幕模式決定了全螢幕功能是使用無邊框全螢幕還是原生全螢幕。",
```suggestion
  "concentration.option.fullscreen_mode.tooltip": "全螢幕模式決定了全螢幕功能要使用無邊框全螢幕還是原生全螢幕。",
```

2024-07-06 09:47 UTC, DeeChael commented
LGTM

2024-07-06 09:48 UTC, merged